package com.skb.course.domain;

import java.util.Date;

public class CourseKnowledgeDO {

	public CourseKnowledgeDO() {
	}

	public CourseKnowledgeDO(Integer courseId, Integer knowledgeId) {
		this.courseId = courseId;
		this.knowledgeId = knowledgeId;

	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column course_knowledge.id
	 *
	 * @mbggenerated
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column course_knowledge.course_id
	 *
	 * @mbggenerated
	 */
	private Integer courseId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column course_knowledge.knowledge_id
	 *
	 * @mbggenerated
	 */
	private Integer knowledgeId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column course_knowledge.status
	 *
	 * @mbggenerated
	 */
	private Byte status;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column course_knowledge.create_time
	 *
	 * @mbggenerated
	 */
	private Date createTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column course_knowledge.modify_time
	 *
	 * @mbggenerated
	 */
	private Date modifyTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column course_knowledge.id
	 *
	 * @return the value of course_knowledge.id
	 *
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column course_knowledge.id
	 *
	 * @param id
	 *            the value for course_knowledge.id
	 *
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column course_knowledge.course_id
	 *
	 * @return the value of course_knowledge.course_id
	 *
	 * @mbggenerated
	 */
	public Integer getCourseId() {
		return courseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column course_knowledge.course_id
	 *
	 * @param courseId
	 *            the value for course_knowledge.course_id
	 *
	 * @mbggenerated
	 */
	public void setCourseId(Integer courseId) {
		this.courseId = courseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column course_knowledge.knowledge_id
	 *
	 * @return the value of course_knowledge.knowledge_id
	 *
	 * @mbggenerated
	 */
	public Integer getKnowledgeId() {
		return knowledgeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column course_knowledge.knowledge_id
	 *
	 * @param knowledgeId
	 *            the value for course_knowledge.knowledge_id
	 *
	 * @mbggenerated
	 */
	public void setKnowledgeId(Integer knowledgeId) {
		this.knowledgeId = knowledgeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column course_knowledge.status
	 *
	 * @return the value of course_knowledge.status
	 *
	 * @mbggenerated
	 */
	public Byte getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column course_knowledge.status
	 *
	 * @param status
	 *            the value for course_knowledge.status
	 *
	 * @mbggenerated
	 */
	public void setStatus(Byte status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column course_knowledge.create_time
	 *
	 * @return the value of course_knowledge.create_time
	 *
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column course_knowledge.create_time
	 *
	 * @param createTime
	 *            the value for course_knowledge.create_time
	 *
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column course_knowledge.modify_time
	 *
	 * @return the value of course_knowledge.modify_time
	 *
	 * @mbggenerated
	 */
	public Date getModifyTime() {
		return modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column course_knowledge.modify_time
	 *
	 * @param modifyTime
	 *            the value for course_knowledge.modify_time
	 *
	 * @mbggenerated
	 */
	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}
}