package com.skb.course.domain;

import java.util.Date;

public class SyncCourseDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sync_course.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sync_course.course_id
     *
     * @mbggenerated
     */
    private Integer courseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sync_course.directory_id
     *
     * @mbggenerated
     */
    private Integer directoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sync_course.author
     *
     * @mbggenerated
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sync_course.publish_count
     *
     * @mbggenerated
     */
    private Integer publishCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sync_course.code
     *
     * @mbggenerated
     */
    private Integer code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sync_course.status
     *
     * @mbggenerated
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sync_course.modify_user
     *
     * @mbggenerated
     */
    private Integer modifyUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sync_course.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sync_course.modify_time
     *
     * @mbggenerated
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sync_course.id
     *
     * @return the value of sync_course.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sync_course.id
     *
     * @param id the value for sync_course.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sync_course.course_id
     *
     * @return the value of sync_course.course_id
     *
     * @mbggenerated
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sync_course.course_id
     *
     * @param courseId the value for sync_course.course_id
     *
     * @mbggenerated
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sync_course.directory_id
     *
     * @return the value of sync_course.directory_id
     *
     * @mbggenerated
     */
    public Integer getDirectoryId() {
        return directoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sync_course.directory_id
     *
     * @param directoryId the value for sync_course.directory_id
     *
     * @mbggenerated
     */
    public void setDirectoryId(Integer directoryId) {
        this.directoryId = directoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sync_course.author
     *
     * @return the value of sync_course.author
     *
     * @mbggenerated
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sync_course.author
     *
     * @param author the value for sync_course.author
     *
     * @mbggenerated
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sync_course.publish_count
     *
     * @return the value of sync_course.publish_count
     *
     * @mbggenerated
     */
    public Integer getPublishCount() {
        return publishCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sync_course.publish_count
     *
     * @param publishCount the value for sync_course.publish_count
     *
     * @mbggenerated
     */
    public void setPublishCount(Integer publishCount) {
        this.publishCount = publishCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sync_course.code
     *
     * @return the value of sync_course.code
     *
     * @mbggenerated
     */
    public Integer getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sync_course.code
     *
     * @param code the value for sync_course.code
     *
     * @mbggenerated
     */
    public void setCode(Integer code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sync_course.status
     *
     * @return the value of sync_course.status
     *
     * @mbggenerated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sync_course.status
     *
     * @param status the value for sync_course.status
     *
     * @mbggenerated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sync_course.modify_user
     *
     * @return the value of sync_course.modify_user
     *
     * @mbggenerated
     */
    public Integer getModifyUser() {
        return modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sync_course.modify_user
     *
     * @param modifyUser the value for sync_course.modify_user
     *
     * @mbggenerated
     */
    public void setModifyUser(Integer modifyUser) {
        this.modifyUser = modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sync_course.create_time
     *
     * @return the value of sync_course.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sync_course.create_time
     *
     * @param createTime the value for sync_course.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sync_course.modify_time
     *
     * @return the value of sync_course.modify_time
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sync_course.modify_time
     *
     * @param modifyTime the value for sync_course.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}