package com.skb.course.domain;

import java.util.Date;

public class SyncDirectoryDO {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sync_directory.id
	 *
	 * @mbggenerated
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sync_directory.name
	 *
	 * @mbggenerated
	 */
	private String name;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sync_directory.parent_id
	 *
	 * @mbggenerated
	 */
	private Integer parentId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sync_directory.layer
	 *
	 * @mbggenerated
	 */
	private Integer layer;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sync_directory.subject
	 *
	 * @mbggenerated
	 */
	private String subject;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sync_directory.education
	 *
	 * @mbggenerated
	 */
	private Integer education;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sync_directory.code
	 *
	 * @mbggenerated
	 */
	private Integer code;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sync_directory.status
	 *
	 * @mbggenerated
	 */
	private Byte status;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sync_directory.modify_user
	 *
	 * @mbggenerated
	 */
	private Integer modifyUser;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sync_directory.create_time
	 *
	 * @mbggenerated
	 */
	private Date createTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sync_directory.modify_time
	 *
	 * @mbggenerated
	 */
	private Date modifyTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sync_directory.id
	 *
	 * @return the value of sync_directory.id
	 *
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sync_directory.id
	 *
	 * @param id
	 *            the value for sync_directory.id
	 *
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sync_directory.name
	 *
	 * @return the value of sync_directory.name
	 *
	 * @mbggenerated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sync_directory.name
	 *
	 * @param name
	 *            the value for sync_directory.name
	 *
	 * @mbggenerated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sync_directory.parent_id
	 *
	 * @return the value of sync_directory.parent_id
	 *
	 * @mbggenerated
	 */
	public Integer getParentId() {
		return parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sync_directory.parent_id
	 *
	 * @param parentId
	 *            the value for sync_directory.parent_id
	 *
	 * @mbggenerated
	 */
	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sync_directory.layer
	 *
	 * @return the value of sync_directory.layer
	 *
	 * @mbggenerated
	 */
	public Integer getLayer() {
		return layer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sync_directory.layer
	 *
	 * @param layer
	 *            the value for sync_directory.layer
	 *
	 * @mbggenerated
	 */
	public void setLayer(Integer layer) {
		this.layer = layer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sync_directory.subject
	 *
	 * @return the value of sync_directory.subject
	 *
	 * @mbggenerated
	 */
	public String getSubject() {
		return subject;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sync_directory.subject
	 *
	 * @param subject
	 *            the value for sync_directory.subject
	 *
	 * @mbggenerated
	 */
	public void setSubject(String subject) {
		this.subject = subject == null ? null : subject.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sync_directory.education
	 *
	 * @return the value of sync_directory.education
	 *
	 * @mbggenerated
	 */
	public Integer getEducation() {
		return education;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sync_directory.education
	 *
	 * @param education
	 *            the value for sync_directory.education
	 *
	 * @mbggenerated
	 */
	public void setEducation(Integer education) {
		this.education = education;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sync_directory.code
	 *
	 * @return the value of sync_directory.code
	 *
	 * @mbggenerated
	 */
	public Integer getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sync_directory.code
	 *
	 * @param code
	 *            the value for sync_directory.code
	 *
	 * @mbggenerated
	 */
	public void setCode(Integer code) {
		this.code = code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sync_directory.status
	 *
	 * @return the value of sync_directory.status
	 *
	 * @mbggenerated
	 */
	public Byte getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sync_directory.status
	 *
	 * @param status
	 *            the value for sync_directory.status
	 *
	 * @mbggenerated
	 */
	public void setStatus(Byte status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sync_directory.modify_user
	 *
	 * @return the value of sync_directory.modify_user
	 *
	 * @mbggenerated
	 */
	public Integer getModifyUser() {
		return modifyUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sync_directory.modify_user
	 *
	 * @param modifyUser
	 *            the value for sync_directory.modify_user
	 *
	 * @mbggenerated
	 */
	public void setModifyUser(Integer modifyUser) {
		this.modifyUser = modifyUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sync_directory.create_time
	 *
	 * @return the value of sync_directory.create_time
	 *
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sync_directory.create_time
	 *
	 * @param createTime
	 *            the value for sync_directory.create_time
	 *
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sync_directory.modify_time
	 *
	 * @return the value of sync_directory.modify_time
	 *
	 * @mbggenerated
	 */
	public Date getModifyTime() {
		return modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sync_directory.modify_time
	 *
	 * @param modifyTime
	 *            the value for sync_directory.modify_time
	 *
	 * @mbggenerated
	 */
	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}
}