package com.skb.course.domain;

import java.util.Date;

import com.skb.util.sort.Sortable;

public class TeacherCourseDO implements Sortable {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column teacher_course.id
	 *
	 * @mbggenerated
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column teacher_course.teacher_id
	 *
	 * @mbggenerated
	 */
	private Integer teacherId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column teacher_course.dir_id
	 *
	 * @mbggenerated
	 */
	private Integer dirId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column teacher_course.course_id
	 *
	 * @mbggenerated
	 */
	private Integer courseId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column teacher_course.remark
	 *
	 * @mbggenerated
	 */
	private String remark;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column teacher_course.order_id
	 *
	 * @mbggenerated
	 */
	private Integer orderId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column teacher_course.status
	 *
	 * @mbggenerated
	 */
	private Byte status;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column teacher_course.create_time
	 *
	 * @mbggenerated
	 */
	private Date createTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column teacher_course.modify_time
	 *
	 * @mbggenerated
	 */
	private Date modifyTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column teacher_course.id
	 *
	 * @return the value of teacher_course.id
	 *
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column teacher_course.id
	 *
	 * @param id
	 *            the value for teacher_course.id
	 *
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column teacher_course.teacher_id
	 *
	 * @return the value of teacher_course.teacher_id
	 *
	 * @mbggenerated
	 */
	public Integer getTeacherId() {
		return teacherId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column teacher_course.teacher_id
	 *
	 * @param teacherId
	 *            the value for teacher_course.teacher_id
	 *
	 * @mbggenerated
	 */
	public void setTeacherId(Integer teacherId) {
		this.teacherId = teacherId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column teacher_course.dir_id
	 *
	 * @return the value of teacher_course.dir_id
	 *
	 * @mbggenerated
	 */
	public Integer getDirId() {
		return dirId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column teacher_course.dir_id
	 *
	 * @param dirId
	 *            the value for teacher_course.dir_id
	 *
	 * @mbggenerated
	 */
	public void setDirId(Integer dirId) {
		this.dirId = dirId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column teacher_course.course_id
	 *
	 * @return the value of teacher_course.course_id
	 *
	 * @mbggenerated
	 */
	public Integer getCourseId() {
		return courseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column teacher_course.course_id
	 *
	 * @param courseId
	 *            the value for teacher_course.course_id
	 *
	 * @mbggenerated
	 */
	public void setCourseId(Integer courseId) {
		this.courseId = courseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column teacher_course.remark
	 *
	 * @return the value of teacher_course.remark
	 *
	 * @mbggenerated
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column teacher_course.remark
	 *
	 * @param remark
	 *            the value for teacher_course.remark
	 *
	 * @mbggenerated
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column teacher_course.order_id
	 *
	 * @return the value of teacher_course.order_id
	 *
	 * @mbggenerated
	 */
	public Integer getOrderId() {
		return orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column teacher_course.order_id
	 *
	 * @param orderId
	 *            the value for teacher_course.order_id
	 *
	 * @mbggenerated
	 */
	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column teacher_course.status
	 *
	 * @return the value of teacher_course.status
	 *
	 * @mbggenerated
	 */
	public Byte getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column teacher_course.status
	 *
	 * @param status
	 *            the value for teacher_course.status
	 *
	 * @mbggenerated
	 */
	public void setStatus(Byte status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column teacher_course.create_time
	 *
	 * @return the value of teacher_course.create_time
	 *
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column teacher_course.create_time
	 *
	 * @param createTime
	 *            the value for teacher_course.create_time
	 *
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column teacher_course.modify_time
	 *
	 * @return the value of teacher_course.modify_time
	 *
	 * @mbggenerated
	 */
	public Date getModifyTime() {
		return modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column teacher_course.modify_time
	 *
	 * @param modifyTime
	 *            the value for teacher_course.modify_time
	 *
	 * @mbggenerated
	 */
	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	@Override
	public String toString() {
		return "TeacherCourseDO [id=" + id + ", teacherId=" + teacherId + ", dirId=" + dirId + ", courseId=" + courseId
				+ ", remark=" + remark + ", orderId=" + orderId + ", status=" + status + ", createTime=" + createTime
				+ ", modifyTime=" + modifyTime + "]";
	}

}