package com.skb.course.dao;

import java.util.List;

import com.skb.course.domain.CourseKnowledgeDO;

public interface CourseKnowledgeDAO {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table course_knowledge
	 *
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table course_knowledge
	 *
	 * @mbggenerated
	 */
	int insert(CourseKnowledgeDO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table course_knowledge
	 *
	 * @mbggenerated
	 */
	int insertSelective(CourseKnowledgeDO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table course_knowledge
	 *
	 * @mbggenerated
	 */
	CourseKnowledgeDO selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table course_knowledge
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(CourseKnowledgeDO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table course_knowledge
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKey(CourseKnowledgeDO record);

	/**
	 * 批量插入课程知识点
	 * 
	 * @return
	 */
	int addCourseKnowledgeBatch(List<CourseKnowledgeDO> list);

	/**
	 * 获取一个课程的知识点ID
	 * 
	 * @param courseId
	 *            课程ID
	 * @return
	 */
	List<Integer> queryCourseKnowledgeIdList(Integer courseId);

	/**
	 * 批量删除课程知识点
	 * 
	 * @param list
	 * @return
	 */
	int deleteCourseKnowledgeBatch(List<CourseKnowledgeDO> list);

}