package com.skb.course.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.mybatis.spring.annotation.MapperScan;

import com.skb.course.domain.DocumentDO;

@MapperScan
public interface DocumentDAO {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table document
	 *
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table document
	 *
	 * @mbggenerated
	 */
	int insert(DocumentDO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table document
	 *
	 * @mbggenerated
	 */
	int insertSelective(DocumentDO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table document
	 *
	 * @mbggenerated
	 */
	DocumentDO selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table document
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(DocumentDO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table document
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKey(DocumentDO record);

	/**
	 * 查询目录下文档数量
	 * 
	 * @param dirId
	 *            目录
	 * @return
	 */
	/**
	 * 查询文档数量
	 * @param teacherId
	 * @param dirId 目录
	 * @param permission 权限 0，公开；1，私有; null, 不限制权限
	 * @return
	 */
	int selectDocumentCount(@Param("teacherId") Integer teacherId, @Param("dirId") Integer dirId, @Param("permission") Byte permission);

	/**
	 * 分页查询目录下的文档
	 * 
	 * @param teacherId
	 * @param dirId
	 * @param startIndex
	 * @param endIndex
	 * @return
	 */
	List<DocumentDO> selectDocumentsByDirId(@Param("teacherId") Integer teacherId, @Param("dirId") Integer dirId,
			@Param("startIndex") Integer startIndex, @Param("endIndex") Integer endIndex);
}