package com.skb.course.dao;

import java.util.List;
import java.util.Map;

import org.mybatis.spring.annotation.MapperScan;

import com.skb.course.domain.KnowledgeDO;

@MapperScan
public interface KnowledgeDAO {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table knowledge
	 *
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table knowledge
	 *
	 * @mbggenerated
	 */
	int insert(KnowledgeDO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table knowledge
	 *
	 * @mbggenerated
	 */
	int insertSelective(KnowledgeDO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table knowledge
	 *
	 * @mbggenerated
	 */
	KnowledgeDO selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table knowledge
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(KnowledgeDO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table knowledge
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKey(KnowledgeDO record);

	/**
	 * 查询同步课程目录列表
	 * 
	 * @param map
	 * @return
	 */
	List<KnowledgeDO> queryForList(Map<String, Object> map);
}