package com.skb.course.dao;

import java.util.List;
import java.util.Map;

import org.mybatis.spring.annotation.MapperScan;

import com.skb.course.domain.SyncDirectoryDO;

@MapperScan
public interface SyncDirectoryDAO {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sync_directory
	 *
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sync_directory
	 *
	 * @mbggenerated
	 */
	int insert(SyncDirectoryDO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sync_directory
	 *
	 * @mbggenerated
	 */
	int insertSelective(SyncDirectoryDO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sync_directory
	 *
	 * @mbggenerated
	 */
	SyncDirectoryDO selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sync_directory
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(SyncDirectoryDO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sync_directory
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKey(SyncDirectoryDO record);

	/**
	 * 查询同步课程目录列表
	 * 
	 * @param map
	 * @return
	 */
	List<SyncDirectoryDO> queryForList(Map<String, Object> map);
}