package com.skb.course.dao;

import java.util.List;
import java.util.Map;

import org.mybatis.spring.annotation.MapperScan;

import com.skb.course.domain.SyncCourseDO;

@MapperScan
public interface SyncCourseDAO {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sync_course
	 *
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer courseId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sync_course
	 *
	 * @mbggenerated
	 */
	int insert(SyncCourseDO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sync_course
	 *
	 * @mbggenerated
	 */
	int insertSelective(SyncCourseDO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sync_course
	 *
	 * @mbggenerated
	 */
	SyncCourseDO selectOneByCourseId(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sync_course
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(SyncCourseDO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sync_course
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKey(SyncCourseDO record);

	/**
	 * 查询同步课程数量
	 * 
	 * @param map
	 * @return
	 */
	int queryForListNum(Map<String, Object> map);

	/**
	 * 查询同步课程列表
	 * 
	 * @param map
	 * @return
	 */
	List<SyncCourseDO> queryForList(Map<String, Object> map);

	/**
	 * 新增同步课程转载数
	 * 
	 * @param courseId
	 * @return
	 */
	int updateSyncCoursePublishCount(Integer courseId);

	/**
	 * 获取文件夹下最大排序号
	 * 
	 * @param directoryId
	 * @return
	 */
	int queryMaxCodeForDirectory(Integer directoryId);
}